import React, { useCallback, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  SafeAreaView,
  ScrollView,
  TextInput,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeIn, FadeInRight } from 'react-native-reanimated';

import { ThemedText } from '@src/components/atoms/ThemedText';
import { ThemedView } from '@src/components/atoms/ThemedView';
import { useTheme } from '@src/state/theme/ThemeProvider';
import { useCreatePodcast, type AudioFormat } from '@src/api/hooks/useCreatePodcast';

type WizardStep = 1 | 2 | 3;
type PodcastLength = 5 | 15 | 30 | 60;
type Phase = 'wizard' | 'generating' | 'success' | 'error';
type IoniconName = React.ComponentProps<typeof Ionicons>['name'];

// ─── Quick picks ─────────────────────────────────────────────────────────────

interface QuickPick {
  label: string;
  emoji: string;
}

const QUICK_PICKS: QuickPick[] = [
  { label: 'Bitcoin halving', emoji: '₿' },
  { label: 'Claude 4 release', emoji: '🤖' },
  { label: 'NBA MVP race 2025', emoji: '🏀' },
  { label: 'Fed rate decision', emoji: '🏦' },
  { label: 'Apple Intelligence', emoji: '🍎' },
  { label: 'SpaceX Starship', emoji: '🚀' },
  { label: 'Trump tariffs impact', emoji: '🇺🇸' },
  { label: 'Nvidia earnings', emoji: '📈' },
  { label: 'Taylor Swift Eras Tour', emoji: '🎤' },
  { label: 'OpenAI drama', emoji: '🔥' },
];

// ─── Length options ───────────────────────────────────────────────────────────

interface LengthOption {
  value: PodcastLength;
  label: string;
  sublabel: string;
  description: string;
  icon: IoniconName;
}

const LENGTH_OPTIONS: LengthOption[] = [
  {
    value: 5,
    label: '5 min',
    sublabel: 'Quick brief',
    description: 'Top 3 headlines, no fluff',
    icon: 'flash-outline',
  },
  {
    value: 15,
    label: '15 min',
    sublabel: 'Standard',
    description: 'News + analysis, your daily driver',
    icon: 'headset-outline',
  },
  {
    value: 30,
    label: '30 min',
    sublabel: 'Deep dive',
    description: 'Full coverage with context',
    icon: 'mic-outline',
  },
  {
    value: 60,
    label: '60 min',
    sublabel: 'Full episode',
    description: 'Long-form, comprehensive story',
    icon: 'albums-outline',
  },
];

// ─── Format options ───────────────────────────────────────────────────────────

interface FormatOption {
  id: AudioFormat;
  emoji: string;
  label: string;
  description: string;
  tags: string[];
  selectedBg: string;
  selectedBorder: string;
  iconBg: string;
  checkBg: string;
  tagTone: 'primary' | 'success' | 'danger';
}

const FORMAT_OPTIONS: FormatOption[] = [
  {
    id: 'podcast',
    emoji: '🎙️',
    label: 'Podcast',
    description:
      'Scripted and edited — like a real podcast, generated by Grok in seconds.',
    tags: ['Episodic', 'Polished', 'Scripted'],
    selectedBg: 'bg-primary/10 dark:bg-primaryDark/10',
    selectedBorder: 'border-primary/40 dark:border-primaryDark/40',
    iconBg: 'bg-primary/10 dark:bg-primaryDark/10',
    checkBg: 'bg-primary dark:bg-primaryDark',
    tagTone: 'primary',
  },
  {
    id: 'radio',
    emoji: '📻',
    label: 'Live Radio',
    description:
      'Continuous stream. An AI host narrates the latest X posts on your topic in real time.',
    tags: ['Always on', 'Real-time', 'AI DJ'],
    selectedBg: 'bg-success/10 dark:bg-successDark/10',
    selectedBorder: 'border-success/40 dark:border-successDark/40',
    iconBg: 'bg-success/10 dark:bg-successDark/10',
    checkBg: 'bg-success dark:bg-successDark',
    tagTone: 'success',
  },
  {
    id: 'audiobook',
    emoji: '📖',
    label: 'Audiobook',
    description:
      'Long-form narration. Grok compiles a deep, chapter-style breakdown of your topic.',
    tags: ['Chapter-based', 'Immersive', 'In-depth'],
    selectedBg: 'bg-danger/10 dark:bg-dangerDark/10',
    selectedBorder: 'border-danger/40 dark:border-dangerDark/40',
    iconBg: 'bg-danger/10 dark:bg-dangerDark/10',
    checkBg: 'bg-danger dark:bg-dangerDark',
    tagTone: 'danger',
  },
];

// ─── Step dots ────────────────────────────────────────────────────────────────

function StepDots({ current }: { current: WizardStep }) {
  return (
    <View className="flex-row items-center justify-center gap-2">
      {([1, 2, 3] as WizardStep[]).map((s) => (
        <View
          key={s}
          className={`rounded-full ${
            s === current
              ? 'w-6 h-2 bg-primary dark:bg-primaryDark'
              : s < current
                ? 'w-2 h-2 bg-primary/40 dark:bg-primaryDark/40'
                : 'w-2 h-2 bg-border dark:bg-borderDark'
          }`}
        />
      ))}
    </View>
  );
}

// ─── Step 1: Topic ────────────────────────────────────────────────────────────

function Step1({
  topic,
  onChangeTopic,
}: {
  topic: string;
  onChangeTopic: (t: string) => void;
}) {
  const { tokens } = useTheme();

  return (
    <View className="gap-6">
      <View className="gap-1">
        <ThemedText variant="title">What's your story?</ThemedText>
        <ThemedText variant="body" tone="muted">
          Grok will research X and build your audio around this topic.
        </ThemedText>
      </View>

      <TextInput
        value={topic}
        onChangeText={onChangeTopic}
        placeholder="e.g. Bitcoin halving, GPT-5 release, NBA playoffs..."
        placeholderTextColor={tokens.colors.muted}
        style={{
          fontFamily: 'Nunito_400Regular',
          fontSize: 16,
          color: tokens.colors.foreground,
          backgroundColor: tokens.colors.surface,
          borderWidth: 1,
          borderColor: topic.length > 0 ? tokens.colors.primary : tokens.colors.border,
          borderRadius: 16,
          paddingHorizontal: 16,
          paddingVertical: 14,
        }}
        autoCorrect={false}
        autoCapitalize="words"
      />

      <View className="gap-3">
        <ThemedText variant="caption" tone="muted" className="font-nunito-semibold">
          QUICK PICKS
        </ThemedText>
        <View className="flex-row flex-wrap gap-2">
          {QUICK_PICKS.map((pick) => {
            const selected = topic === pick.label;
            return (
              <Pressable
                key={pick.label}
                onPress={() => onChangeTopic(pick.label)}
                className={`flex-row items-center gap-1.5 px-3 py-2 rounded-full border active:opacity-70 ${
                  selected
                    ? 'bg-primary dark:bg-primaryDark border-primary dark:border-primaryDark'
                    : 'bg-surface dark:bg-surfaceDark border-border dark:border-borderDark'
                }`}
              >
                <ThemedText style={{ fontSize: 13 }}>{pick.emoji}</ThemedText>
                <ThemedText
                  variant="caption"
                  className={`font-nunito-semibold ${selected ? 'text-white' : ''}`}
                >
                  {pick.label}
                </ThemedText>
              </Pressable>
            );
          })}
        </View>
      </View>
    </View>
  );
}

// ─── Step 2: Length ───────────────────────────────────────────────────────────

function Step2({
  length,
  onSelect,
}: {
  length: PodcastLength;
  onSelect: (l: PodcastLength) => void;
}) {
  const { tokens } = useTheme();

  return (
    <View className="gap-6">
      <View className="gap-1">
        <ThemedText variant="title">How long?</ThemedText>
        <ThemedText variant="body" tone="muted">
          Choose how much time you want to spend with your content.
        </ThemedText>
      </View>

      <View className="gap-3">
        {LENGTH_OPTIONS.map((opt) => {
          const selected = length === opt.value;
          return (
            <Pressable
              key={opt.value}
              onPress={() => onSelect(opt.value)}
              className={`flex-row items-center gap-4 rounded-2xl p-4 border active:opacity-80 ${
                selected
                  ? 'bg-primary/10 dark:bg-primaryDark/10 border-primary/40 dark:border-primaryDark/40'
                  : 'bg-surface dark:bg-surfaceDark border-border dark:border-borderDark'
              }`}
            >
              <View
                className={`w-10 h-10 rounded-xl items-center justify-center ${
                  selected ? 'bg-primary dark:bg-primaryDark' : 'bg-primary/10 dark:bg-primaryDark/10'
                }`}
              >
                <Ionicons
                  name={opt.icon}
                  size={20}
                  color={selected ? 'white' : tokens.colors.primary}
                />
              </View>

              <View className="flex-1">
                <View className="flex-row items-baseline gap-2">
                  <ThemedText variant="headline">{opt.label}</ThemedText>
                  <ThemedText variant="caption" tone="muted">
                    {opt.sublabel}
                  </ThemedText>
                </View>
                <ThemedText variant="caption" tone="muted">
                  {opt.description}
                </ThemedText>
              </View>

              <View
                className={`w-6 h-6 rounded-full border-2 items-center justify-center ${
                  selected
                    ? 'bg-primary dark:bg-primaryDark border-primary dark:border-primaryDark'
                    : 'border-border dark:border-borderDark'
                }`}
              >
                {selected && <Ionicons name="checkmark" size={14} color="white" />}
              </View>
            </Pressable>
          );
        })}
      </View>
    </View>
  );
}

// ─── Step 3: Format ───────────────────────────────────────────────────────────

function Step3({
  format,
  onSelect,
}: {
  format: AudioFormat;
  onSelect: (f: AudioFormat) => void;
}) {
  return (
    <View className="gap-6">
      <View className="gap-1">
        <ThemedText variant="title">Choose your format</ThemedText>
        <ThemedText variant="body" tone="muted">
          How should Grok deliver the content?
        </ThemedText>
      </View>

      <View className="gap-4">
        {FORMAT_OPTIONS.map((opt) => {
          const selected = format === opt.id;
          return (
            <Pressable
              key={opt.id}
              onPress={() => onSelect(opt.id)}
              className={`rounded-3xl p-5 gap-3 border active:opacity-80 ${
                selected
                  ? `${opt.selectedBg} ${opt.selectedBorder}`
                  : 'bg-surface dark:bg-surfaceDark border-border dark:border-borderDark'
              }`}
            >
              <View className="flex-row items-center justify-between">
                <View
                  className={`w-12 h-12 rounded-2xl items-center justify-center ${
                    selected ? opt.iconBg : 'bg-primary/5 dark:bg-primaryDark/5'
                  }`}
                >
                  <ThemedText style={{ fontSize: 24 }}>{opt.emoji}</ThemedText>
                </View>
                {selected && (
                  <View
                    className={`w-6 h-6 rounded-full items-center justify-center ${opt.checkBg}`}
                  >
                    <Ionicons name="checkmark" size={14} color="white" />
                  </View>
                )}
              </View>

              <View className="gap-1">
                <ThemedText variant="headline">{opt.label}</ThemedText>
                <ThemedText variant="caption" tone="muted">
                  {opt.description}
                </ThemedText>
              </View>

              <View className="flex-row flex-wrap gap-2">
                {opt.tags.map((tag) => (
                  <View
                    key={tag}
                    className={`px-2.5 py-1 rounded-full ${opt.iconBg}`}
                  >
                    <ThemedText
                      variant="caption"
                      tone={opt.tagTone}
                      className="font-nunito-semibold"
                    >
                      {tag}
                    </ThemedText>
                  </View>
                ))}
              </View>
            </Pressable>
          );
        })}
      </View>
    </View>
  );
}

// ─── Generating view ──────────────────────────────────────────────────────────

function GeneratingView({ topic }: { topic: string }) {
  return (
    <Animated.View entering={FadeIn.duration(300)} className="flex-1 items-center justify-center gap-6 px-8">
      <View className="w-20 h-20 rounded-full bg-primary/10 dark:bg-primaryDark/10 items-center justify-center">
        <ActivityIndicator size="large" color="#2563EB" />
      </View>

      <View className="gap-2 items-center">
        <ThemedText variant="title" className="text-center">
          Generating your podcast
        </ThemedText>
        <ThemedText variant="body" tone="muted" className="text-center">
          Grok is scraping X, writing your script, and producing the audio for{' '}
          <ThemedText variant="body" tone="primary">
            {topic}
          </ThemedText>
          .
        </ThemedText>
      </View>

      <ThemedText variant="caption" tone="muted" className="text-center">
        This usually takes 30–60 seconds.
      </ThemedText>
    </Animated.View>
  );
}

// ─── Success view ─────────────────────────────────────────────────────────────

function SuccessView({
  topic,
  lengthMinutes,
  format,
  onCreateAnother,
}: {
  topic: string;
  lengthMinutes: PodcastLength;
  format: AudioFormat;
  onCreateAnother: () => void;
}) {
  const formatLabel = FORMAT_OPTIONS.find((o) => o.id === format)?.label ?? format;

  return (
    <Animated.View entering={FadeIn.duration(400)} className="flex-1 items-center justify-center gap-6 px-8">
      <View className="w-20 h-20 rounded-full bg-success/10 dark:bg-successDark/10 items-center justify-center">
        <Ionicons name="checkmark-circle" size={48} color="#16A34A" />
      </View>

      <View className="gap-2 items-center">
        <ThemedText variant="title" className="text-center">
          Your podcast is ready
        </ThemedText>
        <ThemedText variant="body" tone="muted" className="text-center">
          {topic}
        </ThemedText>
        <View className="flex-row items-center gap-2 mt-1">
          <View className="bg-primary/10 dark:bg-primaryDark/10 px-2.5 py-1 rounded-full">
            <ThemedText variant="caption" tone="primary" className="font-nunito-semibold">
              {lengthMinutes} min
            </ThemedText>
          </View>
          <View className="bg-success/10 dark:bg-successDark/10 px-2.5 py-1 rounded-full">
            <ThemedText variant="caption" tone="success" className="font-nunito-semibold">
              {formatLabel}
            </ThemedText>
          </View>
        </View>
      </View>

      <ThemedText variant="caption" tone="muted" className="text-center">
        Head to your Library to listen.
      </ThemedText>

      <Pressable
        onPress={onCreateAnother}
        className="px-8 py-3 rounded-pill border border-border dark:border-borderDark active:opacity-70"
      >
        <ThemedText variant="headline" tone="muted">
          Create Another
        </ThemedText>
      </Pressable>
    </Animated.View>
  );
}

// ─── Error view ───────────────────────────────────────────────────────────────

function ErrorView({
  message,
  onRetry,
}: {
  message: string | null;
  onRetry: () => void;
}) {
  return (
    <Animated.View entering={FadeIn.duration(300)} className="flex-1 items-center justify-center gap-6 px-8">
      <View className="w-20 h-20 rounded-full bg-danger/10 dark:bg-dangerDark/10 items-center justify-center">
        <Ionicons name="alert-circle" size={48} color="#DC2626" />
      </View>

      <View className="gap-2 items-center">
        <ThemedText variant="title" className="text-center">
          Something went wrong
        </ThemedText>
        {message && (
          <ThemedText variant="caption" tone="muted" className="text-center">
            {message}
          </ThemedText>
        )}
      </View>

      <Pressable
        onPress={onRetry}
        className="px-8 py-3 rounded-pill bg-primary dark:bg-primaryDark active:opacity-90"
      >
        <ThemedText variant="headline" className="text-white">
          Try Again
        </ThemedText>
      </Pressable>
    </Animated.View>
  );
}

// ─── Main screen ──────────────────────────────────────────────────────────────

export const CreateChannelTabScreen: React.FC = () => {
  const { tokens } = useTheme();
  const { createPodcast, isPending, error, createdPodcast, reset } = useCreatePodcast();

  const [step, setStep] = useState<WizardStep>(1);
  const [topic, setTopic] = useState('');
  const [length, setLength] = useState<PodcastLength>(15);
  const [format, setFormat] = useState<AudioFormat>('podcast');
  const [hasSubmitted, setHasSubmitted] = useState(false);

  const phase = useMemo<Phase>(() => {
    if (!hasSubmitted) return 'wizard';
    if (isPending) return 'generating';
    if (createdPodcast) return 'success';
    return 'error';
  }, [hasSubmitted, isPending, createdPodcast]);

  const canProceed = useMemo(() => {
    if (step === 1) return topic.trim().length > 0;
    return true;
  }, [step, topic]);

  const isLastStep = step === 3;

  const handleNext = useCallback(() => {
    if (isLastStep) {
      setHasSubmitted(true);
      createPodcast({ topic, lengthMinutes: length, format });
    } else {
      setStep((s) => (s + 1) as WizardStep);
    }
  }, [isLastStep, createPodcast, topic, length, format]);

  const handleBack = useCallback(() => {
    if (step > 1) setStep((s) => (s - 1) as WizardStep);
  }, [step]);

  const handleReset = useCallback(() => {
    setStep(1);
    setTopic('');
    setLength(15);
    setFormat('podcast');
    setHasSubmitted(false);
    reset();
  }, [reset]);

  const handleRetry = useCallback(() => {
    setHasSubmitted(false);
    reset();
  }, [reset]);

  // ── Non-wizard phases ──────────────────────────────────────────────────────

  if (phase === 'generating') {
    return (
      <ThemedView className="flex-1">
        <SafeAreaView className="flex-1">
          <GeneratingView topic={topic} />
        </SafeAreaView>
      </ThemedView>
    );
  }

  if (phase === 'success') {
    return (
      <ThemedView className="flex-1">
        <SafeAreaView className="flex-1">
          <SuccessView
            topic={topic}
            lengthMinutes={length}
            format={format}
            onCreateAnother={handleReset}
          />
        </SafeAreaView>
      </ThemedView>
    );
  }

  if (phase === 'error') {
    return (
      <ThemedView className="flex-1">
        <SafeAreaView className="flex-1">
          <ErrorView message={error} onRetry={handleRetry} />
        </SafeAreaView>
      </ThemedView>
    );
  }

  // ── Wizard phase ───────────────────────────────────────────────────────────

  return (
    <ThemedView className="flex-1">
      <SafeAreaView className="flex-1">
        <KeyboardAvoidingView
          className="flex-1"
          behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        >
          {/* Header */}
          <View className="px-6 pt-6 pb-4 gap-4">
            <View className="flex-row items-center gap-3">
              {step > 1 && (
                <Pressable onPress={handleBack} accessibilityRole="button">
                  <Ionicons name="arrow-back" size={24} color={tokens.colors.foreground} />
                </Pressable>
              )}
              <ThemedText variant="title" className="flex-1">
                New Podcast
              </ThemedText>
              <ThemedText variant="caption" tone="muted">
                {step} of 3
              </ThemedText>
            </View>
            <StepDots current={step} />
          </View>

          <ScrollView
            className="flex-1"
            contentContainerStyle={{ paddingHorizontal: 24, paddingBottom: 32 }}
            showsVerticalScrollIndicator={false}
            keyboardDismissMode="on-drag"
          >
            <Animated.View key={step} entering={FadeInRight.duration(280)}>
              {step === 1 && <Step1 topic={topic} onChangeTopic={setTopic} />}
              {step === 2 && <Step2 length={length} onSelect={setLength} />}
              {step === 3 && <Step3 format={format} onSelect={setFormat} />}
            </Animated.View>
          </ScrollView>

          {/* Footer CTA */}
          <View className="px-6 pb-8 pt-4 border-t border-border dark:border-borderDark">
            <Pressable
              onPress={handleNext}
              disabled={!canProceed}
              className={`py-4 rounded-pill items-center justify-center active:opacity-90 ${
                canProceed
                  ? 'bg-primary dark:bg-primaryDark'
                  : 'bg-border dark:bg-borderDark'
              }`}
              accessibilityRole="button"
            >
              <ThemedText
                variant="headline"
                className={canProceed ? 'text-white' : ''}
                tone={canProceed ? 'default' : 'muted'}
              >
                {isLastStep ? '🎙️  Generate Podcast' : 'Continue'}
              </ThemedText>
            </Pressable>
          </View>
        </KeyboardAvoidingView>
      </SafeAreaView>
    </ThemedView>
  );
};
