import type { AudioFormat, ContentTone, LiveRadioStyle } from '@src/api/hooks/useCreateAudio';

import type { IoniconName, PodcastLength } from './types';

export interface QuickPick {
  label: string;
  emoji: string;
}

export const QUICK_PICKS: QuickPick[] = [
  { label: 'Bitcoin halving', emoji: '₿' },
  { label: 'Claude 4 release', emoji: '🤖' },
  { label: 'NBA MVP race 2025', emoji: '🏀' },
  { label: 'Fed rate decision', emoji: '🏦' },
  { label: 'Apple Intelligence', emoji: '🍎' },
  { label: 'SpaceX Starship', emoji: '🚀' },
  { label: 'Trump tariffs impact', emoji: '🇺🇸' },
  { label: 'Nvidia earnings', emoji: '📈' },
  { label: 'Taylor Swift Eras Tour', emoji: '🎤' },
  { label: 'OpenAI drama', emoji: '🔥' },
];

export interface LengthOption {
  value: PodcastLength;
  label: string;
  sublabel: string;
  description: string;
  icon: IoniconName;
}

export interface ToneOption {
  value: ContentTone;
  label: string;
  description: string;
  icon: IoniconName;
}

export const TONE_OPTIONS: ToneOption[] = [
  {
    value: 'conversational',
    label: 'Conversational',
    description: 'Relaxed hosts, natural back-and-forth energy.',
    icon: 'chatbubbles-outline',
  },
  {
    value: 'news',
    label: 'News briefing',
    description: 'Crisp, factual, like a morning update.',
    icon: 'newspaper-outline',
  },
  {
    value: 'educational',
    label: 'Educational',
    description: 'Clear explanations — teach without talking down.',
    icon: 'school-outline',
  },
  {
    value: 'storytelling',
    label: 'Storytelling',
    description: 'Narrative arcs, scene-setting, immersive.',
    icon: 'book-outline',
  },
  {
    value: 'humorous',
    label: 'Humorous',
    description: 'Wit and levity where it fits the topic.',
    icon: 'happy-outline',
  },
];

export const LENGTH_OPTIONS: LengthOption[] = [
  {
    value: 5,
    label: '5 min',
    sublabel: 'Quick brief',
    description: 'Top 3 headlines, no fluff',
    icon: 'flash-outline',
  },
  {
    value: 15,
    label: '15 min',
    sublabel: 'Standard',
    description: 'News + analysis, your daily driver',
    icon: 'headset-outline',
  },
  {
    value: 30,
    label: '30 min',
    sublabel: 'Deep dive',
    description: 'Full coverage with context',
    icon: 'mic-outline',
  },
  {
    value: 60,
    label: '60 min',
    sublabel: 'Full episode',
    description: 'Long-form, comprehensive story',
    icon: 'albums-outline',
  },
];

export interface FormatOption {
  id: AudioFormat;
  emoji: string;
  label: string;
  description: string;
  tags: string[];
  selectedBg: string;
  selectedBorder: string;
  iconBg: string;
  checkBg: string;
  tagTone: 'primary' | 'success' | 'danger';
}

export const FORMAT_OPTIONS: FormatOption[] = [
  {
    id: 'podcast',
    emoji: '🎙️',
    label: 'Podcast',
    description:
      'Scripted and edited — like a real podcast, generated by Grok in seconds.',
    tags: ['Episodic', 'Polished', 'Scripted'],
    selectedBg: 'bg-primary/10 dark:bg-primaryDark/10',
    selectedBorder: 'border-primary/40 dark:border-primaryDark/40',
    iconBg: 'bg-primary/10 dark:bg-primaryDark/10',
    checkBg: 'bg-primary dark:bg-primaryDark',
    tagTone: 'primary',
  },
  {
    id: 'radio',
    emoji: '📻',
    label: 'Live Radio',
    description:
      'Always-on stream. Next you’ll pick a live radio style — sports includes ESPN play-by-play plus X.',
    tags: ['Always on', 'Real-time', 'Styles'],
    selectedBg: 'bg-success/10 dark:bg-successDark/10',
    selectedBorder: 'border-success/40 dark:border-successDark/40',
    iconBg: 'bg-success/10 dark:bg-successDark/10',
    checkBg: 'bg-success dark:bg-successDark',
    tagTone: 'success',
  },
  {
    id: 'audiobook',
    emoji: '📖',
    label: 'Audiobook',
    description:
      'Long-form narration. Grok compiles a deep, chapter-style breakdown of your topic.',
    tags: ['Chapter-based', 'Immersive', 'In-depth'],
    selectedBg: 'bg-danger/10 dark:bg-dangerDark/10',
    selectedBorder: 'border-danger/40 dark:border-dangerDark/40',
    iconBg: 'bg-danger/10 dark:bg-dangerDark/10',
    checkBg: 'bg-danger dark:bg-dangerDark',
    tagTone: 'danger',
  },
];

export interface LiveRadioStyleOption {
  value: LiveRadioStyle;
  label: string;
  description: string;
  emoji: string;
  icon: IoniconName;
}

export const LIVE_RADIO_OTHER_STYLES: LiveRadioStyleOption[] = [
  {
    value: 'news_desk',
    label: 'News desk',
    description: 'Tight headlines and breaking updates — wire-speed energy.',
    emoji: '📰',
    icon: 'newspaper-outline',
  },
  {
    value: 'talk_radio',
    label: 'Talk radio',
    description: 'Hot takes, debates, and caller-style riffs on your topic.',
    emoji: '📣',
    icon: 'mic-outline',
  },
  {
    value: 'open_format',
    label: 'Open format',
    description: 'Looser AI host — roams across X and weaves whatever’s trending.',
    emoji: '🎛️',
    icon: 'radio-outline',
  },
];
